on:
  pull_request:
  push:
    branches: [main]

jobs:

  it-tests-use-input-required-values-only:
    name: "IT Test - Providing only mandatory fields should work"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Given the gh-action is used with only mandatory fields
        id: execution
        uses: ./
        with:
          url: "https://postman-echo.com/post"
      - uses: nick-fields/assert-action@aa0067e01f0f6545c31755d6ca128c5a3a14f6bf # v2
        name: Then outputs.status value must be 200 as this URL exists
        with:
          expected: '200'
          actual: ${{ steps.execution.outputs.status }}
          comparison: exact



  it-tests:
    name: "All IT Tests have to pass"
    runs-on: ubuntu-latest
    if: always()
    needs:
      # Add your tests here so that they prevent the merge of broken changes
      - it-tests-use-input-required-values-only
    steps:
      - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
